// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARTUcU_azBG8PRNt68_UVjjAEe4uhgA34',
    appId: '1:166492237528:web:f48236bd3bc6fcb4c271ad',
    messagingSenderId: '166492237528',
    projectId: 'mi-aplicacion-gotica',
    authDomain: 'mi-aplicacion-gotica.firebaseapp.com',
    storageBucket: 'mi-aplicacion-gotica.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZY9GXuPTKxDBpDIxrN7X3r6K9uHoXTvs',
    appId: '1:166492237528:android:1c6ff835c5d0977ac271ad',
    messagingSenderId: '166492237528',
    projectId: 'mi-aplicacion-gotica',
    storageBucket: 'mi-aplicacion-gotica.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxDYT6OYwFaZa0MSE3zFA_BsXdjfarNns',
    appId: '1:166492237528:ios:e90a93ee638c1c2bc271ad',
    messagingSenderId: '166492237528',
    projectId: 'mi-aplicacion-gotica',
    storageBucket: 'mi-aplicacion-gotica.firebasestorage.app',
    iosBundleId: 'com.example.miAplicacionGotica',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxDYT6OYwFaZa0MSE3zFA_BsXdjfarNns',
    appId: '1:166492237528:ios:e90a93ee638c1c2bc271ad',
    messagingSenderId: '166492237528',
    projectId: 'mi-aplicacion-gotica',
    storageBucket: 'mi-aplicacion-gotica.firebasestorage.app',
    iosBundleId: 'com.example.miAplicacionGotica',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARTUcU_azBG8PRNt68_UVjjAEe4uhgA34',
    appId: '1:166492237528:web:b9bdedf88771f673c271ad',
    messagingSenderId: '166492237528',
    projectId: 'mi-aplicacion-gotica',
    authDomain: 'mi-aplicacion-gotica.firebaseapp.com',
    storageBucket: 'mi-aplicacion-gotica.firebasestorage.app',
  );
}
